name: CI

on:
  push:
    branches:
      - master

jobs:
  run-pitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install maven
        uses: xlui/action-maven-cli@v1

      - name: install dependencies
        run: mvn clean install

      - name: Run pitests
        run: mvn org.pitest:pitest-maven:mutationCoverage
